apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  selector:
    matchLabels:
      app: config

  template:
    metadata:
      labels:
        app: config

    spec:
      containers:
      - name: config
        image: {{DOCKER_HUB_USER}}/config
        env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: config-service-password
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: notification-service-password
          - name: STATISTICS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: statistics-service-password
          - name: ACCOUNT_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: account-service-password
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: mongodb-connection-string
        ports:
        - containerPort: 8888

---
kind: Service
apiVersion: v1
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
  - port: 8888
    targetPort: 8888
  