apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-service
spec:
  selector:
    matchLabels:
      app: statistics-service

  template:
    metadata:
      labels:
        app: statistics-service

    spec:
      containers:
      - name: statistics-service
        image: {{DOCKER_HUB_USER}}/statistics-service
        env:
          - name: CONFIG_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: config-service-password
          - name: NOTIFICATION_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: notification-service-password
          - name: STATISTICS_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: statistics-service-password
          - name: ACCOUNT_SERVICE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: account-service-password
          - name: MONGODB_CONNECTION_STRING
            valueFrom:
              secretKeyRef:
                name: piggy-metrics-secret
                key: mongodb-connection-string
        ports:
          - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: statistics-service
spec:
  selector:
    app: statistics-service
  ports:
  - port: 80
    targetPort: 80
  